# Generated by Django 3.1.6 on 2021-02-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='사용자 이름')),
                ('email', models.EmailField(max_length=128, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=64, verbose_name='사용자 비밀번호')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='사용자 가입날짜')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='피드 제목')),
                ('content', models.TextField(max_length=100, verbose_name='피드 내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='피드 생성날짜')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='login_api.user', verbose_name='특정 사용자')),
            ],
            options={
                'db_table': 'feed',
            },
        ),
    ]
