# Generated by Django 3.1.6 on 2021-02-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0002_auto_20210206_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='title',
        ),
    ]
